### PR TITLE
[Bug fix]: async offload RPC to prevent client expiration and shm_not_mappedFix/issue 1711 async offload rpc

### LINKED ISSUE #1711: [Bug]: SSD offloading failed I0320 11:44:12.713064  1965 real_client.cpp:2127] client_id=10684295550290858646-16823729354007242427, action=client_expired
### Bug Report

Follow standalone deployment: https://kvcache-ai.github.io/Mooncake/deployment/ssd-offload.html

Tested qwen3-8b with two L20 instances within a Docker container.

When the in-memory cache size hit upper-bound. The store client output error logs:
```
I0320 11:44:00.798640  1969 real_client.cpp:1807] Time taken for batch_get_into: 10852us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.821834  1969 real_client.cpp:1807] Time taken for batch_get_into: 13408us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.833235  1969 real_client.cpp:1807] Time taken for batch_get_into: 10962us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.850095  1969 real_client.cpp:1807] Time taken for batch_get_into: 11671us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.861250  1969 real_client.cpp:1807] Time taken for batch_get_into: 10620us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.884661  1969 real_client.cpp:1807] Time taken for batch_get_into: 13415us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.896236  1969 real_client.cpp:1807] Time taken for batch_get_into: 11031us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.919435  1969 real_client.cpp:1807] Time taken for batch_get_into: 13454us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.931099  1969 real_client.cpp:1807] Time taken for batch_get_into: 11056us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:00.948236  1969 real_client.cpp:1807] Time taken for batch_get_into: 6905us, read store: 0us, with memory key count: 118, offload key count: 0
I0320 11:44:01.019526  1969 real_client.cpp:1807] Time taken for batch_get_into: 18498us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.031678  1969 real_client.cpp:1807] Time taken for batch_get_into: 11570us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.048856  1969 real_client.cpp:1807] Time taken for batch_get_into: 11903us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.060530  1969 real_client.cpp:1807] Time taken for batch_get_into: 11188us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.083736  1969 real_client.cpp:1807] Time taken for batch_get_into: 13720us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.095507  1969 real_client.cpp:1807] Time taken for batch_get_into: 11241us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.118474  1969 real_client.cpp:1807] Time taken for batch_get_into: 12703us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.130359  1969 real_client.cpp:1807] Time taken for batch_get_into: 11377us, read store: 0us, with memory key count: 256, offload key count: 0
I0320 11:44:01.148136  1969 real_client.cpp:1807] Time taken for batch_get_into: 8084us, read store: 0us, with memory key count: 124, offload key count: 0
E0320 11:44:01.694228  1962 file_storage.cpp:424] Key not found: bfc6b014872398302512179f7723fd27479498416bf4460c7ae56508a6cffd2a_0_v
E0320 11:44:01.694275  1962 file_storage.cpp:306] BatchQuerySlices failed with error: OBJECT_NOT_FOUND
I0320 11:44:02.566584  1969 real_client.cpp:2387] Time taken for batch_get_into_offload_object_internal: 61ms, with target_rpc_service_addr: 0.0.0.0:50052, key size: 146gc ttl: 5000ms.
I0320 11:44:12.713064  1965 real_client.cpp:2127] client_id=10684295550290858646-16823729354007242427, action=client_expired
2026-03-20 11:44:32.567017 ERROR    [1671] [coro_rpc_client.hpp:1359] read rpc head failed, error msg:Operation aborted.. close the socket.value=125
E0320 11:44:32.567056  1671 real_client.cpp:2448] RPC call failed: Connection timed out
E0320 11:44:32.567454  1969 real_client.cpp:2423] Failed to invoke batch_get_offload_object, client_addr = 0.0.0.0:50053, error is: RPC_FAIL
E0320 11:44:32.567502  1969 real_client.cpp:2375] Batch get offload object failed with error: RPC_FAIL
E0320 11:44:32.567513  1969 real_client.cpp:1789] Batch get store object failed with error: RPC_FAIL
I0320 11:44:32.567549  1969 real_client.cpp:1807] Time taken for batch_get_into: 30062723us, read store: 30062118us, with memory key count: 0, offload key count: 256
E0320 11:44:33.213884  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.215492  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.220103  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.221275  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.222333  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.223364  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.224387  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.224967  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.226471  1969 real_client.cpp:1581] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.233217  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped
E0320 11:44:33.234208  1969 real_client.cpp:1414] client_id=10684295550290858646-16823729354007242427, error=shm_not_mapped

```
after this, output infinite shm_not_mapped.

master log:
```
 B
I0320 11:43:36.697383  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 18.16 GB / 32.00 GB (56.7%) | SSD Storage: 0 B / 0 B | Keys: 264410 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1118/1118, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=1085/0/1088, Item=264408/264440), PutEnd:(Req=1084/0/1084, Item=264152/264152), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=340/0/340, Item=147764/147764), ExistKey:(Req=1525/0/1525, Item=376604/376604), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=0/0, keys=0, size=0 B | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:43:46.697547  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 26.37 GB / 32.00 GB (82.4%) | SSD Storage: 0 B / 0 B | Keys: 384114 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1138/1138, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=1600/0/1603, Item=384112/384144), PutEnd:(Req=1599/0/1599, Item=383856/383856), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=820/0/820, Item=316834/316834), ExistKey:(Req=2542/0/2542, Item=624806/624806), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=0/0, keys=0, size=0 B | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:43:56.697721  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 30.15 GB / 32.00 GB (94.2%) | SSD Storage: 0 B / 0 B | Keys: 468575 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1158/1158, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2035/0/2038, Item=484568/484600), PutEnd:(Req=2033/0/2033, Item=484184/484184), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1083/0/1083, Item=432310/432310), ExistKey:(Req=3071/0/3071, Item=750364/750364), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=2/2, keys=45394, size=3.12 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:44:06.697906  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.43 GB / 32.00 GB (92.0%) | SSD Storage: 0 B / 0 B | Keys: 528680 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1178/1178, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2427/0/2430, Item=574718/574750), PutEnd:(Req=2427/0/2427, Item=574718/574718), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1318/2/1320, Item=541246/541376), ExistKey:(Req=3556/0/3556, Item=865218/865218), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:44:16.698081  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.43 GB / 32.00 GB (92.0%) | SSD Storage: 0 B / 0 B | Keys: 528680 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1198/1198, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2427/0/2430, Item=574718/574750), PutEnd:(Req=2427/0/2427, Item=574718/574718), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1371/2/1373, Item=567746/567876), ExistKey:(Req=3556/0/3556, Item=865218/865218), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:44:26.698262  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.43 GB / 32.00 GB (92.0%) | SSD Storage: 0 B / 0 B | Keys: 528680 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1218/1218, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2427/0/2430, Item=574718/574750), PutEnd:(Req=2427/0/2427, Item=574718/574718), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1371/2/1373, Item=567746/567876), ExistKey:(Req=3556/0/3556, Item=865218/865218), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:44:36.698405  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.43 GB / 32.00 GB (92.0%) | SSD Storage: 0 B / 0 B | Keys: 528680 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1238/1238, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2427/0/2430, Item=574718/574750), PutEnd:(Req=2427/0/2427, Item=574718/574718), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1371/2/1373, Item=567746/567876), ExistKey:(Req=3934/0/3934, Item=952796/952796), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:44:46.698559  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.43 GB / 32.00 GB (92.0%) | SSD Storage: 0 B / 0 B | Keys: 528680 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1258/1258, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2427/0/2430, Item=574718/574750), PutEnd:(Req=2427/0/2427, Item=574718/574718), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1371/2/1373, Item=567746/567876), ExistKey:(Req=4401/0/4401, Item=1068106/1068106), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:44:56.698719  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.43 GB / 32.00 GB (92.0%) | SSD Storage: 0 B / 0 B | Keys: 528680 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1278/1278, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2427/0/2430, Item=574718/574750), PutEnd:(Req=2427/0/2427, Item=574718/574718), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1371/2/1373, Item=567746/567876), ExistKey:(Req=4573/0/4573, Item=1108442/1108442), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:45:06.698896  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.71 GB / 32.00 GB (92.8%) | SSD Storage: 0 B / 0 B | Keys: 532774 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1298/1298, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2444/0/2447, Item=578812/578844), PutEnd:(Req=2444/0/2444, Item=578812/578812), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1373/2/1375, Item=568258/568388), ExistKey:(Req=4859/0/4859, Item=1178382/1178382), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B
I0320 11:45:16.699059  1822 rpc_service.cpp:41] Master Metrics: Mem Storage: 29.71 GB / 32.00 GB (92.8%) | SSD Storage: 0 B / 0 B | Keys: 532774 (soft-pinned: 0) | Clients: 2 | Requests (Success/Total): PutStart=2/2, PutEnd=2/2, PutRevoke=0/0, Get=2/2, Exist=2/2, Del=0/0, DelAll=0/0, Ping=1318/1318, CopyStart=0/0, CopyEnd=0/0, CopyRevoke=0/0, MoveStart=0/0, MoveEnd=0/0, MoveRevoke=0/0 | Batch Requests (Req=Success/PartialSuccess/Total, Item=Success/Total): PutStart:(Req=2444/0/2447, Item=578812/578844), PutEnd:(Req=2444/0/2444, Item=578812/578812), PutRevoke:(Req=0/0/0, Item=0/0), Get:(Req=1381/2/1383, Item=572258/572388), ExistKey:(Req=5100/0/5100, Item=1239484/1239484), QueryIp:(Req=0/0/0, Item=0/0), Clear:(Req=0/0/0, Item=0/0), CreateMoveTask:(Req=0/0), CreateCopyTask:(Req=0/0), QueryTask=(Req=0/0), FetchTasks=(Req=0/0), MarkTaskToComplete= (Req=0/0),  | Eviction: Success/Attempts=6/6, keys=146150, size=10.04 GB | Discard: Released/Total=0/0, StagingSize=0 B

```

Reproduction script:
```

# mooncake ssd offload
mooncake_master --eviction_high_watermark_ratio=0.95 --enable-offload true > mooncake.log 2>&1 &

for i in {0..1}; do
    port=$((50052 + $i))
    MOONCAKE_OFFLOAD_FILE_STORAGE_PATH=/data/cbs/mooncake_offload_${i} \
    MOONCAKE_OFFLOAD_STORAGE_BACKEND_DESCRIPTOR=bucket_storage_backend \
    MOONCAKE_OFFLOAD_TOTAL_SIZE_LIMIT_BYTES=34359738368 \
    MOONCAKE_BUCKET_EVICTION_POLICY="lru" \
    mooncake_client \
        --master_server_address=127.0.0.1:50051 \
        --host=0.0.0.0 \
        --protocol="tcp"  \
        --device_names="eth0" \
        --port=${port} \
        --global_segment_size="16 GB" \
        --enable_offload=true  \
        --metadata_server="P2PHANDSHAKE" > store_${i}.log 2>&1 &
done

for i in {0..1}; do
    store_port=$((50052 + $i))
    port=$((30001 + $i))
    CUDA_VISIBLE_DEVICES=$i python -m sglang.launch_server \
        --enable-hierarchical-cache \
        --hicache-storage-backend mooncake \
        --model-path Qwen3-8B \
        --tp 1 --mem-fraction-static 0.6 --watchdog-timeout 1000 --host 0.0.0.0 --port $port \
        --hicache-storage-backend-extra-config '{"standalone_storage": true, "client_server_address": "127.0.0.1:'$store_port'"}' > sglang_${i}.log 2>&1 &
done

python -m sglang_router.launch_router \
  --worker-urls http://127.0.0.1:30001 http://127.0.0.1:30002 \
  --policy round_robin \
  --host 0.0.0.0 --port 30000 > router.log 2>&1 &
```

client:
```
# cd /sgl-workspace/sglang/benchmark/hicache
python bench_multiturn.py --model-path /root/workspace/data_dir/Qwen3-8B --host 127.0.0.1 --disable-auto-run --request-rate 16 --request-length 1024 --output-length 64
```

### Before submitting...

- [ ] Ensure you searched for relevant issues and read the [documentation]

### PR DESCRIPTION
**Pull request by zhangzuo21**
## Module

- [ ] Transfer Engine (`mooncake-transfer-engine`)
- [✅ ] Mooncake Store (`mooncake-store`)
- [ ] Mooncake EP (`mooncake-ep`)
- [ ] Integration (`mooncake-integration`)
- [ ] P2P Store (`mooncake-p2p-store`)
- [ ] Python Wheel (`mooncake-wheel`)
- [ ] PyTorch Backend (`mooncake-pg`)
- [ ] Mooncake RL (`mooncake-rl`)
- [ ] CI/CD
- [ ] Docs
- [ ] Other

## Type of Change

- [✅ ] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other

## Checklist

- [✅ ] I have performed a self-review of my own code.
- [✅ ] I have formatted my own code using `./scripts/code_format.sh` before submitting.
- [ ] I have updated the documentation.
- [ ] I have added tests to prove my changes are effective.

## Summary

Fixes #1711

When SSD offload is enabled with multiple mooncake_client instances, the coro_rpc IO thread gets blocked by:
1. **Caller side**: `syncAwait` in `invoke_rpc` waiting for remote offload RPC response (30-60s)
2. **Server side**: `file_storage_->BatchGet()` doing synchronous SSD I/O

While the IO thread is blocked, it cannot process `ping` RPCs from dummy clients. After 10s TTL (`DEFAULT_CLIENT_LIVE_TTL_SEC`), the monitor thread marks the client as expired and calls `unmap_shm_internal()`, which permanently erases the SHM context. All subsequent operations fail with `shm_not_mapped` indefinitely.

## Root Cause

`coro_rpc_server` dispatches all RPC handlers on its IO threads. Both `batch_get_into_dummy_helper` (caller) and `batch_get_offload_object` (server) contain blocking operations that prevent the IO thread from returning to the event loop, starving `ping` and other lightweight RPCs.

## Fix

Use `coro_io::post()` to run blocking operations on a dedicated thread pool, converting the RPC handlers to coroutines so the IO thread yields at `co_await` and stays free for `ping`:

- **`batch_get_into_dummy_helper`** → coroutine, posts `batch_get_into_internal` (which contains offload RPC `syncAwait`) to block executor
- **`batch_get_offload_object`** → coroutine, posts `file_storage_->BatchGet()` (SSD I/O) to block executor

The `shared_lock` on `dummy_client_mutex_` is now scoped to only the SHM address translation phase and released before any blocking I/O.

### CODE REVIEW

File: mooncake-store/src/real_client.cpp [hunk 1]
```diff
@@ -1874,58 +1874,69 @@ std::vector<int64_t> RealClient::batch_get_into(
...
+                    << ") "
+                    << "not found in any mapped shared memory for client "
+                    << client_id;
+                co_return std::vector<tl::expected<int64_t, ErrorCode>>(
+                    keys.size(), tl::unexpected(ErrorCode::INVALID_PARAMS));
+            }
         }
-    }
-    return batch_get_into_internal(keys, buffers, sizes);
+    }  // shared_lock released here, before any blocking I/O
```
Comment (maheshrbapatu) [inline mooncake-store/src/real_client.cpp]: The async offload fix looks good for RPC responsiveness, but releasing dummy_client_mutex_ before batch_get_into_internal(...) runs appears to remove the only protection against concurrent unmap_shm_internal(). Since DummyClient::unregister_shm() / teardown can RPC into unmap_shm_internal(), this seems to introduce a use-after-unmap race on the translated SHM buffers. Can we keep the IO thread free while still holding a shared SHM lifetime pin for the full posted operation?

Comment (stmatengss) [reply mooncake-store/src/real_client.cpp]: @zhangzuo21 PTAL. THX!

Comment (zhangzuo21) [reply mooncake-store/src/real_client.cpp]: Good catch! Fixed by wrapping the shared_lock in a shared_ptr and capturing it into the coro_io::post lambda, so the lock is held for the entire
operation. Since ping also takes a shared_lock, this does not block ping — only unmap_shm_internal (unique_lock) will wait until the batch operation
completes.

Comment (maheshrbapatu) [reply mooncake-store/src/real_client.cpp]: LGTM

**Review by ykwd — APPROVED** [review]
