### PR TITLE
[transfer_engine] fix: drain endpoint waiting list via periodic reclaim

### LINKED ISSUE #1845: [Bug]: Potential QP Leak on transfer failure for PD disaggregation scenario
# Environment
Components: Mooncake v0.3.7-post2, SGLang v0.5.7
Use Case: SGLang Prefill-Decode (PD) disaggregation for LLM inference

# Problem Description
We observed that after running for some time in a PD disaggregation scenario, the Prefill side encounters the error: `Failed to create QP: Cannot allocate memory`

# Analysis
1. When Prefill transfers KV cache to Decode, if the transfer engine returns an error:
- SGLang only marks this session as failed in Python layer
- The transfer engine should have already allocated underlying resources (endpoints, QPs) and established connection with Decode side

2. When transfer fails, we want to confirm whether Mooncake:
- Automatically cleans up QP resources
- Automatically cleans up endpoint resources
- Or leaves these resources allocated (potential leak)

# Current Understanding
From code analysis of mooncake-integration/transfer_engine/transfer_engine_py.cpp:
```
int TransferEnginePy::batchTransferSync(...) {
    // Get or create segment handle
    Transport::SegmentHandle handle;
    {
        std::lock_guard<std::mutex> guard(mutex_);
        if (handle_map_.count(target_hostname)) {
            handle = handle_map_[target_hostname];
        } else {
            handle = engine_->openSegment(target_hostname);
            if (handle == (Transport::SegmentHandle)-1) return -1;
            handle_map_[target_hostname] = handle;  // ← Cached permanently
        }
    }

    // ... submit transfer ...

    // On transfer failure
    else if (status.s == TransferStatusEnum::FAILED) {
        engine_->freeBatchID(batch_id);  // Only frees batch ID
        already_freed = true;
        completed = true;
        // Question: Are QP/endpoint resources cleaned up here?
    }

    return -1;
}
```

We notice that:
- freeBatchID(batch_id) is called on failure
- handle_map_[target_hostname] is never removed
- closeSegment() appears to be a no-op (return 0)

### PR DESCRIPTION
**Pull request by ccs1112**
## Description

This closes #1845. Under SGLang PD-disaggregated prefill, `ibv_create_qp` eventually fails with `Cannot allocate memory` and `rdma resource show` reports >20K QPs per NIC, preceded by 1118 endpoint-evicted events.

`SIEVEEndpointStore::reclaimEndpoint` drains `waiting_list_` of quiescent (a.k.a. evicted and deleted) endpoints so their `shared_ptrs` drop, and destructors run `ibv_destroy_qp`. The only production caller was `RdmaContext::endpoint()`. The reclaim piggybacked on new endpoint insertions. Under healthy load, insertions and evictions are coupled, so the list drains in step. Under failure load, such as peers dying or when retries are exhausted, evictions and deletions continue while insertions stop. This causes reclaims to stop firing and `waiting_list_` grows unboundedly. Each accumulated endpoint pins `num_qp_per_ep` QPs against the NIC's pool (1118 x 2..4 ~= enough to exhaust). The reporter's 4x QP asymmetry across NIC groups (22k on `mlx5_00-03` vs. 6k on `mlx5_04-07`) is consistent with this. Eviction load concentrated on the NICs routing to the failing peer.

To fix this, I added a `context_.reclaimEndpoints()` call inside `WorkerPool::monitorWorker`. This is included on the existing `last_reset_ts` heartbeat. The result is that reclaim no longer depends on insertion traffic. The change is minimal. There is one line of behavior change in `worker_pool.cpp` and a thin wrapper method `RdmaContext::reclaimEndpoints()` to delegate to the store.

I also tried adding eager `disconnect()` to `deleteEndpoint`/`evictEndpoint` initially, but it crashes on `rxe` within ~5s with `malloc(): unaligned tcache chunk detected`. I think the `slice->rdma.qp_depth` raw pointer into `wr_depth_list_` becomes dangling when reclaim destroys the endpoint while an in-flight slice still holds it. Fixing that properly requires a shared-ownership refactor of `wr_depth_list_`, which I could do as a follow-up so eager disconnect can be re-added safely.

## Module

- [x] Transfer Engine (`mooncake-transfer-engine`)
- [ ] Mooncake Store (`mooncake-store`)
- [ ] Mooncake EP (`mooncake-ep`)
- [ ] Integration (`mooncake-integration`)
- [ ] P2P Store (`mooncake-p2p-store`)
- [ ] Python Wheel (`mooncake-wheel`)
- [ ] PyTorch Backend (`mooncake-pg`)
- [ ] Mooncake RL (`mooncake-rl`)
- [ ] CI/CD
- [ ] Docs
- [ ] Other

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other

## How Has This Been Tested?

There are 5 new unit tests:
1. `ReclaimDrainsQuiescentEntries` is the base method contract.
2. `ReclaimLeavesActiveEntries` tests that the `hasOutstandingSlice` gate is preserved.
3. `ReclaimIsIdempotentWhenEmpty` tests cadence safety.
4. `LeakManifestsWithoutReclaimCall` reproduces the reporter's 1118-eviction shape and asserts a single reclaim call drains the full backlog.
5. `ReclaimDoesNotRequireActiveMap` guards against a regression that conflates reclaim with insert.

There is 1 new integration test:
1. `endpoint_store_integration_test` constructs a real `RdmaContext`, spawns `monitorWorker`, injects quiescent entries into `waiting_list_`, sleeps, and asserts drainage. I used this bisection to validate the fix. If you remove the new `reclaimEndpoints()` call then this test will fail with the right error message, if you add it back it will pass again.

I ran the full ctest suite. There is one existing failure: `hot_standby_service_test`. I think this is simply due to `etcd` not being available on my system. It's also failing on main, and the code doesn't seem related at all, so I'm flagging this as environmental. Please let me know if you'd like me to take a closer look.

I don't have the hardware to match the original SGLang mlx5 cluster conditions, unfortunately. If you are aware of on-demand spot instances for mlx5, please let me know and I can run this patch there.

This is the test script I used to manually reproduce:
```
sudo apt install -y linux-modules-extra-$(uname -r) rdma-core
sudo modprobe rdma_rxe
sudo rdma link add rxe0 type rxe netdev <your_iface>

mkdir build && cd build
cmake .. -DBUILD_UNIT_TESTS=ON
make -j8
ctest -R endpoint_store_test --output-on-failure
./mooncake-transfer-engine/tests/endpoint_store_integration_test
```

## Checklist

- [x] I have performed a self-review of my own code.
- [x] I have formatted my own code using `./scripts/code_format.sh` before submitting.
- [x] I have updated the documentation.
- [x] I have added tests to prove my changes are effective.

### CODE REVIEW

File: mooncake-transfer-engine/include/transport/rdma_transport/endpoint_store.h [hunk 1]
```diff
@@ -73,6 +74,9 @@ class FIFOEndpointStore : public EndpointStore {
     int disconnectQPs() override;
 
     size_t getTotalQPNumber() override;
+    size_t waitingListSize() const override {
+        return waiting_list_len_.load(std::memory_order_relaxed);
+    }
```
Comment (staryxchen) [inline mooncake-transfer-engine/include/transport/rdma_transport/endpoint_store.h:85]: waiting_list_len_ is declared as atomic<int> but waitingListSize() returns size_t.

File: mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp [hunk 2]
```diff
@@ -493,6 +447,11 @@ void WorkerPool::monitorWorker() {
         auto current_ts = getCurrentTimeInNano();
         if (current_ts - last_reset_ts > 1000000000ll) {
             context_.set_active(true);
+            // Drain endpoint_store_->waiting_list_ even when no new
+            // insertions are happening. Without this, reclaim only runs
+            // from RdmaContext::endpoint() and the waiting list grows
+            // unboundedly under failure load. See issue #1845.
+            context_.reclaimEndpoints();
```
Comment (staryxchen) [inline mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp:454]: Previously `reclaimEndpoint()` was only called from within `insertEndpoint()`, which held `endpoint_map_lock_`. Now it would be called without the lock, please confirm `reclaimEndpoint()`'s lock contract hasn't changed in behavior.

File: mooncake-transfer-engine/include/transport/rdma_transport/rdma_context.h [hunk 3]
```diff
@@ -99,11 +99,18 @@ class RdmaContext {
...
 
+    // Drain the endpoint store's waiting list. Safe to call on any thread;
+    // intended to be invoked periodically from monitorWorker so reclaim is
+    // not gated on new endpoint insertions (which can stall under failure
+    // load while evictions/deletions continue). See issue #1845.
+    void reclaimEndpoints();
+
+    // Raw accessor for the endpoint cache. Null before construct() runs.
+    // Used by integration tests that need to observe waiting_list_ directly.
+    EndpointStore *endpointStore() const { return endpoint_store_.get(); }
```
Comment (staryxchen) [inline mooncake-transfer-engine/include/transport/rdma_transport/rdma_context.h]: This func would expose a raw point to `EndpointStore*`. If this were to be called for other purposes in the future (not just for testing), would it be safe?

File: mooncake-transfer-engine/include/transport/rdma_transport/endpoint_store.h (hunk 1 above)
Comment (ccs1112) [reply mooncake-transfer-engine/include/transport/rdma_transport/endpoint_store.h:85]: Good catch, I promoted the counter to `atomic<size_t` in both FIFO and SIEVE. This is now a clean pass through getter.

File: mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp (hunk 2 above)
Comment (ccs1112) [reply mooncake-transfer-engine/src/transport/rdma_transport/worker_pool.cpp:454]: `reclaimEndpoint()` lock contract has not changed behavior:

- `reclaimEndpoint()` still self-locks using `WriteGuard(endpoint_map_lock_)`.
- The existing caller `rdma_context.cpp:355-356` already had the `insertEndpoint` lock freed by its destructor.
- The new caller in `monitorWorker()` observes the same contract as it holds no `EndpointStore` locks.
- `insertEndpoint()` definitions in FIFO, SIEVE, and UB self-lock and only call `evictEndpoint()`, which is caller-locked. None call `reclaimEndpoint()`.

I added a comment to make this contract clear to future contributors.

File: mooncake-transfer-engine/include/transport/rdma_transport/rdma_context.h (hunk 3 above)
Comment (ccs1112) [reply mooncake-transfer-engine/include/transport/rdma_transport/rdma_context.h]: Yes, I had some concerns about this as well. I decided to remove this pointer and only add the necessary methods to `RdmaContext`: `waitingListSize()` and `testOnlyInsertWaiting(std::shared_ptr<RdmaEndPoint> ep)`.

- `waitingListSize()` returns by value, so there is no pointer to stash.
- `testOnlyInsertWaiting()` takes a `shared_ptr` by value. This removes the raw pointer access across the API boundary.
- `testOnlyInsertWaiting()` is lifted as a virtual function on the `EndpointStore` base interface. This has the added benefit of making the integration test no longer need `dynamic_cast` to `SIEVEEndpointStore`.

**Review by staryxchen — APPROVED** [review]
LGTM if CI pass
