### PR TITLE
[TransferEngine] Fix RDMA GID auto-discovery for IPv6 and reduce spur…

### LINKED ISSUE #1593: [Bug]: No suitable GID found when only IPv6 GIDs is set on rdma devices
### Bug Report

When starting up Mooncake Transfer Engine in an environemnt where all available GIDs do not have a IPv4-mapped-IPv6 GID, Transfer Engine's client returns error like:
```
W0302 09:15:07.980530     7 rdma_context.cpp:581] No suitable GID found on mlx5_bond_1/
E0302 09:15:07.980787     7 rdma_context.cpp:81] Failed to open device mlx5_bond_1 on port  with GID -1
W0302 09:15:07.980791     7 rdma_transport.cpp:656] Disable device mlx5_bond_1
E0302 09:15:07.980793     7 rdma_transport.cpp:662] RdmaTransport: No available RNIC
E0302 09:15:07.980794     7 rdma_transport.cpp:106] RdmaTransport: cannot initialize RDMA resources
E0302 09:15:07.980796     7 transfer_engine_impl.cpp:293] Failed to install RDMA transport, type=rdma
E0302 09:15:07.980798     7 client_service.cpp:288] Failed to initialize transfer engine, rc=-1
E0302 09:15:07.980800     7 client_service.cpp:490] Failed to initialize transfer engine
W0302 09:15:08.933470     7 real_client.cpp:232] Failed to create client on port 14046, retry 20/20
E0302 09:15:09.033545     7 real_client.cpp:239] Failed to create client after 20 retries
``` 

All available GIDs of the rdma device look like this:
```
$ ibv_devinfo -d mlx5_bond_0 -v
...
GID[  0]:               fe80:0000:0000:0000:0225:9dff:fe33:33aa, RoCE v1
GID[  1]:               fe80::225:9dff:fe33:33aa, RoCE v2
GID[  2]:               2001:0db8:0810:0000:0000:0000:0000:0001, RoCE v1
GID[  3]:               2001:db8:810::1, RoCE v2
GID[  4]:               fe80:0db8:0810:0000:0000:0000:0000:0001, RoCE v1
GID[  5]:               fe80:db8:810::1, RoCE v2
```

Explicitly set `MC_GID_INDEX=3` works well, but I think auto discovery should also work correctly

My entrypoint command and environment variables:
```
$ python -m mooncake.mooncake_store_service --port 8081
```

```yaml
 - name: MOONCAKE_MASTER
    value: "s-sglang-demo-mooncake-master:50051"
  - name: MOONCAKE_TE_META_DATA_SERVER
    value: "http://s-sglang-demo-mooncake-master:8080/metadata"
  - name: MOONCAKE_GLOBAL_SEGMENT_SIZE
    value: "5gb"
  - name: MOONCAKE_LOCAL_BUFFER_SIZE
     value: "4194304"
  - name: MOONCAKE_PROTOCOL
    value: "rdma" #support tcp, rdma
  - name: MOONCAKE_DEVICE
    value: ""
  - name: MC_GID_INDEX
    value: "3"
```

### Before submitting...

- [x] Ensure you searched for relevant issues and read the [documentation]

### PR DESCRIPTION
**Pull request by stmatengss**
…ious errors

Fixes #1593 and #1592

Changes:
1. Accept all RoCE v2 GIDs (both IPv4-mapped and pure IPv6) instead of only IPv4-mapped GIDs. This allows Transfer Engine to work in IPv6-only environments.

2. Stop querying GID indices on first failure instead of iterating through all 256 possible indices. This eliminates spurious 'Failed to query GID' error logs when devices have fewer GIDs.

3. Allow user-specified GIDs without network devices. When MC_GID_INDEX is explicitly set, log a warning but continue initialization instead of failing. Users setting this variable know their configuration.

## Module

- [x] Transfer Engine (`mooncake-transfer-engine`)
- [ ] Mooncake Store (`mooncake-store`)
- [ ] Mooncake EP (`mooncake-ep`)
- [ ] Integration (`mooncake-integration`)
- [ ] P2P Store (`mooncake-p2p-store`)
- [ ] Python Wheel (`mooncake-wheel`)
- [ ] PyTorch Backend (`mooncake-pg`)
- [ ] Mooncake RL (`mooncake-rl`)
- [ ] CI/CD
- [ ] Docs
- [ ] Other

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Breaking change
- [ ] Documentation update
- [ ] Other

## Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have formatted my own code using `./scripts/code_format.sh` before submitting.
- [ ] I have updated the documentation.
- [ ] I have added tests to prove my changes are effective.

### CODE REVIEW

File: mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp [hunk 1]
```diff
@@ -447,13 +447,11 @@ GidNetworkState RdmaContext::findBestGidIndex(const std::string &device_name,
...
-            PLOG(ERROR) << "Failed to query GID " << i << " on " << device_name
-                        << "/" << port;
-            continue;  // if gid is invalid ibv_query_gid_ex() will return !0
+            // Reached end of valid GID indices
+            break;
         }
 
-        if ((ipv6_addr_v4mapped((struct in6_addr *)gid_entry.gid.raw) &&
-             gid_entry.gid_type == IBV_GID_TYPE_ROCE_V2) ||
+        if (gid_entry.gid_type == IBV_GID_TYPE_ROCE_V2 ||
```
Comment (alogfans) [inline mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp]: We originally add this restriction to avoid finding loopback GID if the network only supports IPv4. So it's better to find V4 GID first, the fallback to V6.

Comment (stmatengss) [reply mooncake-transfer-engine/src/transport/rdma_transport/rdma_context.cpp]: OK

**Comment by alogfans** [comment]
@stmatengss I will merge it after fixing the code format issue.

**Comment by stmatengss** [comment]
@copilot+claude-opus-4.6 fix code format issue

**Comment by alogfans** [comment]
After changing code format, I think it will be LGTM.

**Comment by stmatengss** [comment]
Fixed. Fall-back path: ipv4 => ipv4 w/o network => ipv6 => ipv6 w/o network. PTAL. @alogfans
